dbt_workshop:
  outputs:
    dev:
      type: postgres
      host: postgres_dwh
      user: postgres
      password: postgres
      port: 5432
      dbname: warehouse
      schema: dev
    ci:
      type: postgres
      host: postgres_dwh
      user: postgres
      password: postgres
      port: 5432
      dbname: warehouse
      schema: ci
  target: dev
